version: '3'
services:
  marzban:
    image: gozargah/marzban:latest
    restart: always
    environment:
      - Uvicorn_Port=8000
      - SUDO_USERNAME=admin
      - SUDO_PASSWORD=Sina2020302m
    ports:
      - "8000:8000"
    volumes:
      - marzban_data:/var/lib/marzban

  mirza-bot:
    image: mirzapanel/bot:latest
    restart: always
    depends_on:
      - marzban
    environment:
      - BOT_TOKEN=8554688879:AAH5-wu96RQ36kgAXa0iJ60NTFvchhdpubs
      - PANEL_URL=http://marzban:8000
      - PANEL_USERNAME=admin
      - PANEL_PASSWORD=Sina2020302m
      - ADMIN_ID=7769294933

volumes:
  marzban_data:
